import React from 'react';
import { createRoot } from 'react-dom/client';
import { capabilities, worlds } from './data/registryFixtures';
import './styles.css';

function currentWorld() { const match = location.pathname.match(/^\/worlds\/([^/]+)/); return match ? worlds.find(w => w.id === match[1]) : undefined; }
function Actions() { return <div className="actions"><button>Play</button><button>Verify</button><button>Contribute</button><button>Fork</button></div>; }
function Directory() { return <section><h2>World Directory</h2><div className="grid">{worlds.map(w => <article className="card" key={w.id}><h3><a href={`/worlds/${w.id}`}>{w.name}</a></h3><p>{w.description}</p><dl><dt>Category</dt><dd>{w.category}</dd><dt>Proof status</dt><dd>{w.proofStatus}</dd><dt>Population</dt><dd>{w.population}</dd><dt>Governance</dt><dd>{w.governance}</dd></dl><strong>Contributor opportunities</strong><ul>{w.opportunities.map(o => <li key={o}>{o}</li>)}</ul></article>)}</div></section>; }
function Detail() { const w = currentWorld(); if (!w) return <Directory />; return <section className="card hero"><p><a href="/worlds">← Browse Worlds</a></p><h2>{w.name}</h2><p>{w.description}</p><Actions /><dl><dt>world.evr identifier</dt><dd>{w.worldEvr}</dd><dt>Operator</dt><dd>{w.operator}</dd><dt>Proof status</dt><dd>{w.proofStatus}</dd><dt>Lineage</dt><dd>{w.lineage}</dd><dt>Governance</dt><dd>{w.governance}</dd><dt>Treasury health</dt><dd>{w.treasury}</dd><dt>Capabilities</dt><dd>{w.capabilities.join(', ')}</dd></dl><h3>Contributor opportunities</h3><ul>{w.opportunities.map(o => <li key={o}>{o}</li>)}</ul></section>; }
function FoundingWorlds() { return <section className="card hero"><h2>Founding Worlds</h2><p>Ten founding world slots are reserved for teams proving portable, verifiable, persistent worlds in public.</p><ol>{Array.from({length:10},(_,i)=><li key={i}>{i===0?'Arena Vanguard — candidate accepted for reference proofs':'Open founding world slot'}</li>)}</ol><button>Apply for Founding Worlds</button><h3>Contributor opportunities</h3><p>Operators, designers, artists, verifier authors, and capability builders can join founding teams.</p></section>; }
function Marketplace() { return <section><h2>Capability Marketplace</h2><div className="grid">{capabilities.map(c => <article className="card" key={c.name}><h3>{c.name}</h3><dl><dt>Author</dt><dd>{c.author}</dd><dt>Version</dt><dd>{c.version}</dd><dt>Worlds using it</dt><dd>{c.worldsUsing}</dd><dt>Reward model</dt><dd>{c.rewardModel}</dd><dt>Verification status</dt><dd>{c.verification}</dd></dl></article>)}</div></section>; }
function App() { const path = location.pathname; return <main><header className="hero"><p>EverArcade</p><h1>world.evr</h1><p>Portable, verifiable, persistent worlds. Come build worlds with us.</p><nav><a href="/worlds">Browse Worlds</a><a href="/founding-worlds">Apply for Founding Worlds</a><a href="/capabilities">Capabilities</a><a href="/worlds/arena-vanguard">Verify a World</a></nav></header>{path.startsWith('/capabilities')?<Marketplace/>:path.startsWith('/founding-worlds')?<FoundingWorlds/>:path.startsWith('/worlds/')?<Detail/>:<Directory/>}</main>; }

createRoot(document.getElementById('root')!).render(<App />);
