const POLL_MS = 1200;
const MAX_EVENTS = 120;
const params = new URLSearchParams(location.search);
const publicMode = params.get("mode") || "seed";
const state = { lastState: null, lastVerify: null, seenCombat: new Set(), combat: [], commitments: [], demoMode: true, speed: 1, labels: true };
const $ = id => document.getElementById(id);
const canvas = $("arenaCanvas");
const ctx = canvas.getContext("2d");

async function fetchJson(path) { const r = await fetch(path, { cache: "no-store" }); if (!r.ok) throw new Error(`${path} returned ${r.status}`); return r.json(); }
async function loadSeed() { return fetchJson("../../../release/demo-production/demo-world-seed.json").catch(() => fetchJson("./demo-world-seed.json")); }
async function fetchAuthoritativeState() {
  let world, verify, seed;
  try {
    seed = await loadSeed();
    if (publicMode === "live") {
      [world, verify] = await Promise.all([fetchJson("/state").catch(() => fetchJson("/world-state")), fetchJson("/verify").catch(() => fetchJson("/status"))]);
      state.demoMode = false;
    } else {
      world = demoWorldFromSeed(seed);
      verify = { ok: true, roots: { stateRoot: seed.commitments.state_root, receiptRoot: seed.commitments.receipt_root, worldHash: seed.commitments.world_hash, continuityRoot: seed.commitments.continuity_root } };
      state.demoMode = true;
    }
    state.seed = seed;
  } catch (error) { setConnection(false, error.message); return; }
  state.lastState = normalizeState(world, state.seed);
  state.lastVerify = normalizeVerify(verify, state.lastState);
  rememberCommitment(state.lastState, state.lastVerify);
  render(); setConnection(true);
}
function normalizeState(raw, seed = {}) {
  const feed = raw.feed ?? raw.worldStateFeed ?? raw;
  const players = Object.values(feed.players ?? raw.players ?? {}).map(p => ({ id: p.playerId ?? p.id ?? "unknown", x: Number(p.position?.x ?? p.x ?? 0), y: Number(p.position?.y ?? p.y ?? 0), zone: p.position?.zone ?? p.zone ?? "Arena", health: Number(p.health ?? p.hp ?? 100), score: Number(p.score ?? p.xp ?? 0), connected: p.connected !== false && p.connectionStatus !== "disconnected", inventory: p.inventory ?? { items: [], last_event: "none" }, trail: p.trail ?? [], lastAction: p.last_action ?? p.lastAction ?? "observe" }));
  const journal = raw.journal ?? raw.replay ?? raw.entries ?? seed.events ?? [];
  const combatEvents = [...(raw.combat_events ?? raw.combatEvents ?? []), ...journal.filter(e => `${e.type ?? e.label ?? e}`.includes("attack"))];
  for (const e of combatEvents) addCombat(e, feed.tick ?? raw.tick ?? 0);
  return { tick: Number(feed.tick ?? raw.tick ?? 0), epoch: Number(feed.epoch ?? raw.epoch ?? seed.world?.epoch ?? 1), players, enemies: Object.values(feed.enemies ?? raw.enemies ?? {}), entities: Object.values(feed.entities ?? raw.entities ?? seed.world?.entities ?? {}), regions: seed.world?.regions ?? [], structures: seed.world?.structures ?? [], resources: seed.world?.resources ?? [], historicalRecords: seed.world?.historical_records ?? {}, worldTimeline: seed.world?.world_timeline ?? [], ruins: seed.ruins ?? [], worldAgeDays: Number(seed.world?.world_age_days ?? 0), worldAgeTicks: Number(seed.world?.world_age_ticks ?? feed.tick ?? raw.tick ?? 0), journal, events: seed.events ?? journal, market: seed.market, governance: seed.governance, replayStatus: raw.replayStatus ?? "REFERENCE", journalSize: Number(raw.journalSize ?? journal.length ?? 0), receiptCount: Number(raw.receipt_count ?? seed.world?.receipt_count ?? journal.length) };
}
function demoWorldFromSeed(seed) { return { ...seed.world, journal: seed.events, combat_events: seed.events.filter(e => e.type === "attack"), replayStatus: publicMode.toUpperCase(), journalSize: seed.events.length }; }
function normalizeVerify(raw, normalized) { const roots = raw.roots ?? raw.commitment ?? raw; const ok = raw.ok ?? raw.verified ?? true; return { verified: Boolean(ok), status: ok ? "VERIFIED" : "FAILED", stateRoot: roots.stateRoot ?? roots.state_root ?? `state:arena-vanguard:tick:${normalized.tick}`, receiptRoot: roots.receiptRoot ?? roots.receipt_root ?? `receipt:arena-vanguard:entries:${normalized.receiptCount}`, worldHash: roots.worldHash ?? roots.world_hash ?? `world:arena-vanguard:players:${normalized.players.length}`, continuityRoot: roots.continuityRoot ?? roots.continuity_root ?? "continuity:arena-vanguard:live" }; }
function short(v) { return String(v ?? "—").replace(/^(.{18}).+(.{8})$/, "$1…$2"); }
function addCombat(event, fallbackTick) { const text = typeof event === "string" ? event : (event.label ?? event.description ?? `${event.attacker ?? "player"} attacked ${event.target ?? "target"}`); const tick = event.tick ?? fallbackTick; const key = `${tick}:${text}`; if (state.seenCombat.has(key)) return; state.seenCombat.add(key); state.combat.unshift({ tick, text, damage: event.damage ?? text.match(/(\d+) damage/)?.[1] ?? 28, at: new Date().toLocaleTimeString() }); state.combat = state.combat.slice(0, MAX_EVENTS); }
function rememberCommitment(world, verify) { const record = { tick: world.tick, ...verify }; if (state.commitments[0]?.stateRoot === record.stateRoot) return; state.commitments.unshift(record); state.commitments = state.commitments.slice(0, 80); }
function setConnection(ok, error = "") { $("connectionDot").className = `dot ${ok ? "dot-ok" : "dot-fail"}`; $("connectionStatus").textContent = ok ? "Reference projection connected" : "Projection unavailable"; $("lastRefresh").textContent = ok ? `Mode ${publicMode} · updated ${new Date().toLocaleTimeString()}` : error; }
function render() { const world = state.lastState, verify = state.lastVerify; if (!world || !verify) return; drawArena(world); renderRuntime(world, verify); renderVerification(verify); renderPlayers(world.players); renderTimeline(world.events); renderFeed(world); renderOperators(world, verify); renderHistory(world); renderCommitments(); }
function drawArena(world) { const w = canvas.width, h = canvas.height, cx = w/2, cy = h/2, cell = 48; ctx.clearRect(0,0,w,h); ctx.fillStyle="#050d18"; ctx.fillRect(0,0,w,h); ctx.strokeStyle="rgba(96,165,250,.18)"; for(let x=cx%cell;x<w;x+=cell){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke();} for(let y=cy%cell;y<h;y+=cell){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke();} ctx.strokeStyle="rgba(53,228,138,.55)"; ctx.lineWidth=3; ctx.strokeRect(78,58,w-156,h-116); drawRegions(world); ctx.strokeStyle="rgba(180,140,255,.35)"; ctx.beginPath(); ctx.arc(cx,cy,250,0,Math.PI*2); ctx.stroke(); ctx.fillStyle="#91a6bf"; ctx.font="12px ui-sans-serif"; ["NW REGION","NE REGION","SW REGION","SE REGION","SPAWN α","SPAWN β","OPERATOR OBSERVATION RING"].forEach((t,i)=>ctx.fillText(t,[96,640,96,640,120,730,376][i],[92,92,560,560,145,505,82][i])); world.entities.forEach(e=>drawEntity(e)); world.enemies.forEach(e=>drawEntity({...e,type:"enemy"})); world.players.forEach(p=>drawPlayer(p)); }
function drawRegions(world){ const regions=world.regions??[]; const colors=["rgba(53,228,138,.10)","rgba(96,165,250,.10)","rgba(180,140,255,.12)","rgba(255,209,102,.10)"]; regions.forEach((r,i)=>{ const [x1,y1,x2,y2]=r.bounds; const a=xy(x1,y2), b=xy(x2,y1); ctx.fillStyle=colors[i%colors.length]; ctx.strokeStyle="rgba(238,246,255,.18)"; ctx.fillRect(a[0],a[1],b[0]-a[0],b[1]-a[1]); ctx.strokeRect(a[0],a[1],b[0]-a[0],b[1]-a[1]); ctx.fillStyle="#eef6ff"; ctx.font="13px ui-sans-serif"; ctx.fillText(r.name, a[0]+12, a[1]+22); }); }
function xy(x,y){return [canvas.width/2+x*48, canvas.height/2-y*48];}
function drawEntity(e){const [px,py]=xy(e.position?.x??e.x??0,e.position?.y??e.y??0); const enemy=e.type==="enemy"; ctx.strokeStyle=enemy?"#ff5b6e":"#ffd166"; ctx.fillStyle=enemy?"rgba(255,91,110,.25)":"rgba(255,209,102,.18)"; ctx.beginPath(); ctx.rect(px-15,py-15,30,30); ctx.fill(); ctx.stroke(); ctx.fillStyle="#eef6ff"; ctx.fillText(`${enemy?"◆":"◇"} ${e.id}`,px-30,py-22); ctx.strokeStyle=enemy?"#ff5b6e":"#ffd166"; ctx.beginPath(); ctx.arc(px,py,22,-Math.PI/2,(-Math.PI/2)+(Math.PI*2*((e.health??100)/100))); ctx.stroke();}
function drawPlayer(p){ const [px,py]=xy(p.x,p.y); ctx.strokeStyle="rgba(96,165,250,.45)"; ctx.beginPath(); (p.trail||[]).forEach((t,i)=>{const q=xy(t.x,t.y); i?ctx.lineTo(...q):ctx.moveTo(...q)}); ctx.lineTo(px,py); ctx.stroke(); ctx.fillStyle=p.connected?"#35e48a":"#64748b"; ctx.beginPath(); ctx.arc(px,py,17,0,Math.PI*2); ctx.fill(); ctx.strokeStyle="#eef6ff"; ctx.stroke(); ctx.shadowColor="#60a5fa"; ctx.shadowBlur=18; ctx.strokeRect(px-24,py-31,48,7); ctx.shadowBlur=0; ctx.fillStyle="#eef6ff"; ctx.fillText(`${p.id} · S${p.score}`,px-30,py-36); ctx.fillText(`HP ${p.health} · ${p.lastAction}`,px-34,py+38);}
function renderRuntime(w,v){ tickValue.textContent=w.tick; worldAgeValue.textContent=`Day ${w.worldAgeDays} / ${w.worldAgeTicks} ticks`; epochValue.textContent=w.epoch; stateRootShort.textContent=short(v.stateRoot); worldHashShort.textContent=short(v.worldHash); receiptCount.textContent=w.receiptCount; journalSize.textContent=w.journalSize; replayStatus.textContent=v.status; playerCount.textContent=w.players.length; runtimeMode.textContent=publicMode.toUpperCase(); }
function renderVerification(v){ verifyBadge.textContent=v.verified?"✓ VERIFIED":"✗ FAILED"; verifyBadge.className=v.verified?"verified":"failed"; roots.innerHTML=[["State Root",v.stateRoot],["Receipt Root",v.receiptRoot],["World Hash",v.worldHash],["Continuity",v.continuityRoot]].map(([l,val])=>`<div class="root-row"><span>${l}</span><code title="${val}">${val}</code><button type="button" data-copy="${val}">Copy</button></div>`).join("");}
function renderPlayers(players){ playerList.innerHTML=players.map(p=>`<article class="player-card ${p.connected?"":"offline"}"><strong>${p.id}<em>${p.connected?"●":"○"}</em></strong><span>(${p.x}, ${p.y}) · ${p.zone} · HP ${p.health}</span><span class="badge">Inventory ${p.inventory.items?.length??0} · ${p.inventory.last_event}</span><div class="bars"><i style="width:${Math.max(0,Math.min(100,p.health))}%"></i></div></article>`).join(""); }
function renderTimeline(events){ const max=Math.max(1,...events.map(e=>e.tick??0)); timelineMarkers.innerHTML=events.map(e=>`<button class="marker ${e.type}" style="left:${Math.min(100,((e.tick??0)/max)*100)}%" title="${e.label}">${e.type}</button>`).join(""); }
function renderFeed(w){ const extras=[w.market&&{type:"trade",label:w.market.status,detail:`${w.market.seller} → ${w.market.buyer} · ${w.market.quantity} ${w.market.item} · ${w.market.currency} credits`}, w.governance&&{type:"vote",label:w.governance.status,detail:`${w.governance.proposal_id} yes ${w.governance.yes} no ${w.governance.no} abstain ${w.governance.abstain}`}].filter(Boolean); eventFeed.innerHTML=[...w.events,...extras].slice(-MAX_EVENTS).reverse().map(e=>`<li class="${e.type}"><b>${e.label}</b><small>tick ${e.tick??w.tick} · ${e.detail??"operator roots matched"}</small></li>`).join(""); combatLine.textContent=state.combat[0]?.text ?? "combat.attack(): awaiting verified receipt"; }
function renderOperators(w,v){ operatorBanner.textContent=state.seed?.operator?.root_match===false?"DIVERGENCE DETECTED":"ROOTS MATCH"; operatorCards.innerHTML=(state.seed?.operator?.nodes??["Operator A","Operator B","Operator C"]).map(n=>`<article><strong>${n}</strong><span>status: healthy</span><code>${short(v.stateRoot)}</code><code>${short(v.worldHash)}</code><span>last tick ${w.tick} · verification ${v.status}</span></article>`).join(""); }
function renderHistory(w){ if(!historyPanel) return; const records=Object.entries(w.historicalRecords??{}).map(([k,v])=>`<li><b>${k.replaceAll("_"," ")}</b><small>${v}</small></li>`).join(""); const days=(w.worldTimeline??[]).map(d=>`<li><b>Day ${d.day}</b><small>tick ${d.tick} · ${d.label}</small></li>`).join(""); const regions=(w.regions??[]).map(r=>`<li><b>${r.name}</b><small>${r.role}</small></li>`).join(""); const ruins=(w.ruins??[]).map(r=>`<li><b>${r.id}</b><small>${r.region} · ${r.label}</small></li>`).join(""); historyPanel.innerHTML=`<div><h3>Historical records</h3><ol class="event-list">${records}</ol></div><div><h3>World timeline</h3><ol class="event-list">${days}</ol></div><div><h3>Regions</h3><ol class="event-list">${regions}</ol></div><div><h3>Ruins</h3><ol class="event-list">${ruins}</ol></div>`; }
function renderCommitments(){ commitmentHistory.innerHTML=state.commitments.map(c=>`<details><summary>Tick ${c.tick} · ${c.status}</summary><code>${c.stateRoot}</code><code>${c.worldHash}</code></details>`).join(""); }
document.addEventListener("click", e=>{ if(e.target?.dataset?.copy){navigator.clipboard?.writeText(e.target.dataset.copy); e.target.textContent="Copied"; setTimeout(()=>e.target.textContent="Copy",900);} if(e.target?.dataset?.speed){state.speed=Number(e.target.dataset.speed); document.querySelectorAll('[data-speed]').forEach(b=>b.classList.toggle('active',b===e.target));}});
fetchAuthoritativeState(); setInterval(fetchAuthoritativeState, POLL_MS);
