const POLL_MS = 1200;
const MAX_EVENTS = 120;
const params = new URLSearchParams(location.search);
const publicMode = params.get("mode") || "seed";
const state = { lastState: null, lastVerify: null, seenCombat: new Set(), combat: [], commitments: [], demoMode: true, speed: 1, labels: true };
const $ = id => document.getElementById(id);
const canvas = $("arenaCanvas");
const ctx = canvas.getContext("2d");

async function fetchJson(path) { const r = await fetch(path, { cache: "no-store" }); if (!r.ok) throw new Error(`${path} returned ${r.status}`); return r.json(); }
async function loadSeed() { return fetchJson("../../../release/demo-production/demo-world-seed.json").catch(() => fetchJson("./demo-world-seed.json")); }
async function fetchAuthoritativeState() {
  let world, verify, seed;
  try {
    seed = await loadSeed();
    if (publicMode === "live") {
      [world, verify] = await Promise.all([fetchJson("/state").catch(() => fetchJson("/world-state")), fetchJson("/verify").catch(() => fetchJson("/status"))]);
      state.demoMode = false;
    } else {
      world = demoWorldFromSeed(seed);
      verify = { ok: true, roots: { stateRoot: seed.commitments.state_root, receiptRoot: seed.commitments.receipt_root, worldHash: seed.commitments.world_hash, continuityRoot: seed.commitments.continuity_root } };
      state.demoMode = true;
    }
    state.seed = seed;
  } catch (error) { setConnection(false, error.message); return; }
  state.lastState = normalizeState(world, state.seed);
  state.lastVerify = normalizeVerify(verify, state.lastState);
  rememberCommitment(state.lastState, state.lastVerify);
  render(); setConnection(true);
}
function normalizeState(raw, seed = {}) {
  const feed = raw.feed ?? raw.worldStateFeed ?? raw;
  const players = Object.values(feed.players ?? raw.players ?? {}).map(p => ({ id: p.playerId ?? p.id ?? "unknown", x: Number(p.position?.x ?? p.x ?? 0), y: Number(p.position?.y ?? p.y ?? 0), zone: p.position?.zone ?? p.zone ?? "Arena", health: Number(p.health ?? p.hp ?? 100), score: Number(p.score ?? p.xp ?? 0), connected: p.connected !== false && p.connectionStatus !== "disconnected", inventory: p.inventory ?? { items: [], last_event: "none" }, trail: p.trail ?? [], lastAction: p.last_action ?? p.lastAction ?? "observe" }));
  const journal = raw.journal ?? raw.replay ?? raw.entries ?? seed.events ?? [];
  const combatEvents = [...(raw.combat_events ?? raw.combatEvents ?? []), ...journal.filter(e => `${e.type ?? e.label ?? e}`.includes("attack"))];
  for (const e of combatEvents) addCombat(e, feed.tick ?? raw.tick ?? 0);
  return { name: raw.name ?? seed.world?.name, objective: raw.objective ?? seed.world?.objective, tick: Number(feed.tick ?? raw.tick ?? 0), epoch: Number(feed.epoch ?? raw.epoch ?? seed.world?.epoch ?? 1), players, enemies: Object.values(feed.enemies ?? raw.enemies ?? {}), entities: Object.values(feed.entities ?? raw.entities ?? seed.world?.entities ?? {}), regions: seed.world?.regions ?? [], structures: seed.world?.structures ?? [], resources: seed.world?.resources ?? [], historicalRecords: seed.world?.historical_records ?? {}, worldTimeline: seed.world?.world_timeline ?? [], ruins: seed.ruins ?? [], worldAgeDays: Number(seed.world?.world_age_days ?? 0), worldAgeTicks: Number(seed.world?.world_age_ticks ?? feed.tick ?? raw.tick ?? 0), journal, events: seed.events ?? journal, market: seed.market, governance: seed.governance, replayStatus: raw.replayStatus ?? "REFERENCE", journalSize: Number(raw.journalSize ?? journal.length ?? 0), receiptCount: Number(raw.receipt_count ?? seed.world?.receipt_count ?? journal.length) };
}
function demoWorldFromSeed(seed) { return { ...seed.world, journal: seed.events, combat_events: seed.events.filter(e => e.type === "attack"), replayStatus: publicMode.toUpperCase(), journalSize: seed.events.length }; }
function normalizeVerify(raw, normalized) { const roots = raw.roots ?? raw.commitment ?? raw; const ok = raw.ok ?? raw.verified ?? true; return { verified: Boolean(ok), status: ok ? "VERIFIED" : "FAILED", stateRoot: roots.stateRoot ?? roots.state_root ?? `state:arena-vanguard:tick:${normalized.tick}`, receiptRoot: roots.receiptRoot ?? roots.receipt_root ?? `receipt:arena-vanguard:entries:${normalized.receiptCount}`, worldHash: roots.worldHash ?? roots.world_hash ?? `world:arena-vanguard:players:${normalized.players.length}`, continuityRoot: roots.continuityRoot ?? roots.continuity_root ?? "continuity:arena-vanguard:live" }; }
function short(v) { return String(v ?? "—").replace(/^(.{18}).+(.{8})$/, "$1…$2"); }
function addCombat(event, fallbackTick) { const text = typeof event === "string" ? event : (event.label ?? event.description ?? `${event.attacker ?? "player"} attacked ${event.target ?? "target"}`); const tick = event.tick ?? fallbackTick; const key = `${tick}:${text}`; if (state.seenCombat.has(key)) return; state.seenCombat.add(key); state.combat.unshift({ tick, text, damage: event.damage ?? text.match(/(\d+) damage/)?.[1] ?? 28, at: new Date().toLocaleTimeString() }); state.combat = state.combat.slice(0, MAX_EVENTS); }
function rememberCommitment(world, verify) { const record = { tick: world.tick, ...verify }; if (state.commitments[0]?.stateRoot === record.stateRoot) return; state.commitments.unshift(record); state.commitments = state.commitments.slice(0, 80); }
function setConnection(ok, error = "") { $("connectionDot").className = `dot ${ok ? "dot-ok" : "dot-fail"}`; $("connectionStatus").textContent = ok ? "Reference projection connected" : "Projection unavailable"; $("lastRefresh").textContent = ok ? `Mode ${publicMode} · updated ${new Date().toLocaleTimeString()}` : error; }
function render() { const world = state.lastState, verify = state.lastVerify; if (!world || !verify) return; drawArena(world); renderRuntime(world, verify); renderVerification(verify); renderTimeline(world.events); renderFeed(world); renderOperators(world, verify); renderMemory(world); renderObjects(world); renderCommitments(); }
function drawArena(world) {
  const w = canvas.width, h = canvas.height;
  ctx.clearRect(0,0,w,h);
  const grd = ctx.createLinearGradient(0,0,w,h); grd.addColorStop(0,"#0b1d2f"); grd.addColorStop(1,"#07111f"); ctx.fillStyle=grd; ctx.fillRect(0,0,w,h);
  ctx.strokeStyle="rgba(139,178,219,.10)"; ctx.lineWidth=1; for(let x=40;x<w;x+=40){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke();} for(let y=40;y<h;y+=40){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke();}
  drawRegions(world);
  (world.resources||[]).forEach(drawResource); (world.structures||[]).forEach(drawStructure); (world.ruins||[]).forEach(drawRuin);
  world.entities.filter(e=>e.type==="structure").forEach(drawStructure); world.enemies.forEach(e=>drawCreature(e)); world.players.forEach(drawPlayer);
}
function drawRegions(world){ const colors={Frontier:"rgba(53,228,138,.12)",Wilderness:"rgba(245,158,11,.13)",Ruins:"rgba(180,140,255,.14)",Citadel:"rgba(96,165,250,.14)"}; (world.regions||[]).forEach(r=>{ const [x1,y1,x2,y2]=r.bounds; const a=xy(x1,y2), b=xy(x2,y1); ctx.fillStyle=colors[r.name]||"rgba(255,255,255,.08)"; ctx.strokeStyle="rgba(238,246,255,.24)"; ctx.lineWidth=2; ctx.fillRect(a[0],a[1],b[0]-a[0],b[1]-a[1]); ctx.strokeRect(a[0],a[1],b[0]-a[0],b[1]-a[1]); ctx.fillStyle="#eef6ff"; ctx.font="700 22px ui-sans-serif"; ctx.fillText(r.name,a[0]+18,a[1]+34); ctx.font="13px ui-sans-serif"; ctx.fillStyle="#b8c7da"; wrapText(r.role,a[0]+18,a[1]+58,Math.max(150,b[0]-a[0]-36),17); }); }
function xy(x,y){return [canvas.width/2+x*58, canvas.height/2-y*58];}
function label(text,x,y){ctx.font="700 13px ui-sans-serif";ctx.fillStyle="#eef6ff";ctx.fillText(text,x,y)}
function wrapText(text,x,y,maxWidth,lineHeight){String(text||"").split(" ").reduce((line,word)=>{const test=line?`${line} ${word}`:word;if(ctx.measureText(test).width>maxWidth){ctx.fillText(line,x,y);y+=lineHeight;return word}return test},"").replace(/^.+$/,line=>ctx.fillText(line,x,y));}
function drawToken(x,y,color,shape){ctx.save();ctx.shadowColor=color;ctx.shadowBlur=15;ctx.fillStyle=color;ctx.strokeStyle="#eef6ff";ctx.lineWidth=2;ctx.beginPath(); if(shape==="square")ctx.rect(x-13,y-13,26,26); else if(shape==="diamond"){ctx.moveTo(x,y-16);ctx.lineTo(x+16,y);ctx.lineTo(x,y+16);ctx.lineTo(x-16,y);ctx.closePath()} else ctx.arc(x,y,15,0,Math.PI*2); ctx.fill();ctx.stroke();ctx.restore()}
function drawResource(r){const pos={Wilderness:[5,-1],Frontier:[-6,0],Citadel:[5,5],Ruins:[-5,-6]}[r.region]||[0,0]; const [x,y]=xy(pos[0]+.45,pos[1]-.35); drawToken(x,y,"#ffd166","diamond"); label(`${r.item} · ${r.quantity}`,x-38,y+34)}
function drawStructure(e){const [x,y]=xy(e.x??({Frontier:-6,Citadel:4,Ruins:-4,Wilderness:4}[e.region]||0),e.y??({Frontier:2,Citadel:6,Ruins:-6,Wilderness:-1}[e.region]||0)); drawToken(x,y,"#60a5fa","square"); label(e.name||e.id,x-46,y-24)}
function drawRuin(r){const pos={Ruins:[-4,-7],Citadel:[2,5],Frontier:[-5,-2],Wilderness:[6,1]}[r.region]||[-4,-6]; const [x,y]=xy(pos[0]-.55,pos[1]+.35); drawToken(x,y,"#b48cff","diamond"); label(r.id,x-58,y+36)}
function drawCreature(e){const [x,y]=xy(e.x??0,e.y??0); drawToken(x,y,"#ff5b6e","circle"); label(`${e.kind||e.id} HP ${e.health??"?"}`,x-56,y-25)}
function drawPlayer(p){ const [x,y]=xy(p.x,p.y); ctx.strokeStyle="rgba(96,165,250,.55)"; ctx.lineWidth=3; ctx.beginPath(); (p.trail||[]).forEach((t,i)=>{const q=xy(t.x,t.y); i?ctx.lineTo(...q):ctx.moveTo(...q)}); ctx.lineTo(x,y); ctx.stroke(); drawToken(x,y,p.connected?"#35e48a":"#64748b","circle"); label(`${p.id} · ${p.zone}`,x-42,y-28); ctx.font="12px ui-sans-serif"; ctx.fillStyle="#dbeafe"; ctx.fillText(`HP ${p.health} · ${p.lastAction}`,x-50,y+36);}
function renderRuntime(w,v){ worldName.textContent=w.name||"Arena Vanguard Frontier"; worldObjective.textContent=w.objective||"Read-only deterministic PvE world projection."; tickValue.textContent=`tick ${w.tick}`; worldAgeValue.textContent=`Day ${w.worldAgeDays}`; epochValue.textContent=w.epoch; receiptCount.textContent=w.receiptCount; journalSize.textContent=w.journalSize; replayStatus.textContent=v.status; playerCount.textContent=w.players.length; runtimeMode.textContent=publicMode.toUpperCase(); }
function renderVerification(v){ verifyBadge.textContent=v.verified?"✓ VERIFIED":"✗ FAILED"; verifyBadge.className=v.verified?"verified":"failed"; roots.innerHTML=[["State Root",v.stateRoot],["Receipt Root",v.receiptRoot],["World Hash",v.worldHash],["Continuity",v.continuityRoot]].map(([l,val])=>`<div class="root-row"><span>${l}</span><code title="${val}">${val}</code><button type="button" data-copy="${val}">Copy</button></div>`).join("");}
function renderPlayers(players){ playerList.innerHTML=players.map(p=>`<article class="player-card ${p.connected?"":"offline"}"><strong>${p.id}<em>${p.connected?"●":"○"}</em></strong><span>(${p.x}, ${p.y}) · ${p.zone} · HP ${p.health}</span><span class="badge">Inventory ${p.inventory.items?.length??0} · ${p.inventory.last_event}</span><div class="bars"><i style="width:${Math.max(0,Math.min(100,p.health))}%"></i></div></article>`).join(""); }
function renderTimeline(events){ const max=Math.max(1,...events.map(e=>e.tick??0)); timelineMarkers.innerHTML=events.map(e=>`<button class="marker ${e.type}" style="left:${Math.min(100,((e.tick??0)/max)*100)}%" title="${e.label}">${e.type}</button>`).join(""); historyTimeline.innerHTML=(state.lastState.worldTimeline||[]).map(d=>`<li><b>Day ${d.day}</b><small>tick ${d.tick} · ${d.label}</small></li>`).join(""); }
function renderFeed(w){ const extras=[w.market&&{type:"trade",label:w.market.status,detail:`${w.market.seller} → ${w.market.buyer} · ${w.market.quantity} ${w.market.item} · ${w.market.currency} credits`}, w.governance&&{type:"vote",label:w.governance.status,detail:`${w.governance.proposal_id} yes ${w.governance.yes} no ${w.governance.no} abstain ${w.governance.abstain}`}].filter(Boolean); eventFeed.innerHTML=[...w.events,...extras].slice(-MAX_EVENTS).reverse().map(e=>`<li class="${e.type}"><b>${plainEvent(e)}</b><small>tick ${e.tick??w.tick} · ${e.detail??"operator roots matched"}</small></li>`).join(""); }
function plainEvent(e){ const label=e.label||"World event"; if(e.type==="return") return "A returning player finds that the world has aged."; if(e.type==="ruin") return "A ruin remains visible because the world remembers an older battle."; if(e.type==="restore") return "The world was restored from checkpoint without resetting history."; if(e.type==="migration") return "The world migrated operators while preserving continuity."; return label.replace(/^[a-z.()]+:\s*/i,""); }
function renderOperators(w,v){ operatorBanner.textContent=state.seed?.operator?.root_match===false?"DIVERGENCE DETECTED":"ROOTS MATCH"; operatorCards.innerHTML=(state.seed?.operator?.nodes??["Operator A","Operator B","Operator C"]).map(n=>`<article><strong>${n}</strong><span>status: healthy</span><code>${short(v.stateRoot)}</code><code>${short(v.worldHash)}</code><span>last tick ${w.tick} · verification ${v.status}</span></article>`).join(""); }
function renderHistory(w){ if(!historyPanel) return; const records=Object.entries(w.historicalRecords??{}).map(([k,v])=>`<li><b>${k.replaceAll("_"," ")}</b><small>${v}</small></li>`).join(""); const days=(w.worldTimeline??[]).map(d=>`<li><b>Day ${d.day}</b><small>tick ${d.tick} · ${d.label}</small></li>`).join(""); const regions=(w.regions??[]).map(r=>`<li><b>${r.name}</b><small>${r.role}</small></li>`).join(""); const ruins=(w.ruins??[]).map(r=>`<li><b>${r.id}</b><small>${r.region} · ${r.label}</small></li>`).join(""); historyPanel.innerHTML=`<div><h3>Historical records</h3><ol class="event-list">${records}</ol></div><div><h3>World timeline</h3><ol class="event-list">${days}</ol></div><div><h3>Regions</h3><ol class="event-list">${regions}</ol></div><div><h3>Ruins</h3><ol class="event-list">${ruins}</ol></div>`; }

function renderMemory(w){ const records=Object.entries(w.historicalRecords??{}).slice(0,7); memoryCards.innerHTML=records.map(([k,v])=>`<article class="memory-card"><b>${k.replaceAll("_"," ")}</b><small>${v}</small></article>`).join(""); }
function renderObjects(w){ const cards=[]; w.players.forEach(p=>cards.push({kind:"player",title:p.id,meta:`${p.zone} · HP ${p.health}`,body:`Inventory: ${(p.inventory.items||[]).join(", ")||"empty"}`,badge:p.connected?"online player":"offline, world persisted"})); w.enemies.forEach(e=>cards.push({kind:"creature",title:e.kind||e.id,meta:e.region||"World",body:`${e.id} is alive with ${e.health} health.`,badge:"creature"})); (w.resources||[]).forEach(r=>cards.push({kind:"resource",title:r.item,meta:r.region,body:`${r.quantity} available; regenerates every ${r.regenerates_every_ticks} ticks.`,badge:"resource node"})); (w.structures||[]).forEach(s=>cards.push({kind:"structure",title:s.name||s.id,meta:s.region,body:`${s.condition||"standing"}; aged ${s.age_ticks} ticks.`,badge:"structure"})); (w.ruins||[]).forEach(r=>cards.push({kind:"ruin",title:r.id,meta:r.region,body:r.label,badge:`created tick ${r.created_tick}`})); objectCards.innerHTML=cards.map(c=>`<article class="object-card ${c.kind}"><span>${c.kind}</span><b>${c.title}</b><p>${c.meta}</p><p>${c.body}</p><em class="badge">${c.badge}</em></article>`).join(""); }
function renderCommitments(){ commitmentHistory.innerHTML=state.commitments.map(c=>`<details><summary>Tick ${c.tick} · ${c.status}</summary><code>${c.stateRoot}</code><code>${c.worldHash}</code></details>`).join(""); }
document.addEventListener("click", e=>{ if(e.target?.dataset?.copy){navigator.clipboard?.writeText(e.target.dataset.copy); e.target.textContent="Copied"; setTimeout(()=>e.target.textContent="Copy",900);} if(e.target?.dataset?.speed){state.speed=Number(e.target.dataset.speed); document.querySelectorAll('[data-speed]').forEach(b=>b.classList.toggle('active',b===e.target));}});
fetchAuthoritativeState(); setInterval(fetchAuthoritativeState, POLL_MS);
