#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"
export CARGO_BUILD_JOBS="${CARGO_BUILD_JOBS:-1}"
CARGO_FLAGS=()
for arg in "$@"; do
  case "$arg" in
    --offline|--locked|--frozen) CARGO_FLAGS+=("$arg") ;;
    *) echo "unknown argument: $arg" >&2; exit 2 ;;
  esac
done
REPORT="deployment/reports/operator_validation_run.md"
for guide in install bootstrap deploy recover upgrade rollback; do
  test -f "docs/operators/${guide}.md"
done
cargo test -p execution-core --test evernode_deployment_tests test_operator_bootstrap "${CARGO_FLAGS[@]}"
cat > "$REPORT" <<'REPORT_EOF'
# Operator Validation Run

status: passed
install workflow: present
bootstrap workflow: present
deployment workflow: present
recovery workflow: present
upgrade workflow: present
rollback workflow: present
REPORT_EOF
echo "operator validation passed; report=$REPORT"

bash scripts/generate_evernode_packages.sh
for op in deploy start stop restart recover verify; do
  deployment/evernode/operations.sh "$op" >/dev/null
done
mkdir -p deployment/reports
cat > deployment/reports/operator_readiness_report.md <<'RPT'
# Operator Readiness Report

## Startup Workflow
Ready: operators install dependencies, verify package hashes, and bootstrap from reproducible manifests.

## Deployment Workflow
Ready: Arena Vanguard runtime, world, and deployment packages are deployed from real tarball artifacts.

## Operator Workflow
Ready: deploy, start, stop, restart, recover, and verify operations are covered by the local operator validation gate.

## Recovery Workflow
Ready: runtime crash, node restart, checkpoint restore, and world restore compare the same replay root, world root, and continuity root.

## Upgrade Workflow
Partially Ready: deterministic upgrade and rollback workflow is documented; production automation remains external to this repository.

- deployment artifacts: generated by `scripts/generate_evernode_packages.sh`
- source control policy: generated `.tar.gz` and `.sig` files are not source controlled
- operations covered: deploy, start, stop, restart, recover, verify
- package rebuildability: validated
- operator readiness: validated
RPT
CARGO_BUILD_JOBS=1 cargo test -p execution-core --test evernode_deployment_tests "$@"

echo "operator validation complete"
