#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

bash scripts/build_evernode_packages.sh
(cd deployment/evernode/runtime && sha256sum -c packages.sha256 >/dev/null)
CARGO_BUILD_JOBS=1 cargo test -p execution-core --test evernode_deployment_tests "$@"

mkdir -p deployment/reports
cat > deployment/reports/evernode_launch_gate.md <<'RPT'
# EverNode Launch Gate

- deployment artifacts: generated by `scripts/build_evernode_packages.sh`
- source control policy: generated `.tar.gz` and `.sig` files are not source controlled
- checksum manifest: `deployment/evernode/runtime/packages.sha256`
- package validation: generated artifacts, signatures, and hashes validated
- deployment gate: validated
RPT
cp deployment/reports/evernode_launch_gate.md deployment/reports/evernode_deployment_gate.md

echo "evernode deployment gate complete"
