#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

bash scripts/build_evernode_packages.sh
bash scripts/run_xrpl_anchor_validation.sh "$@"

mkdir -p deployment/reports
cat > deployment/reports/xrpl_launch_gate.md <<'RPT'
# XRPL Launch Gate

- deployment artifacts: generated by `scripts/build_evernode_packages.sh`
- source control policy: generated `.tar.gz` and `.sig` files are not source controlled
- XRPL runtime submission boundary: external operator only
- anchor validation: validated
RPT

echo "anchor validation complete"
