#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

bash scripts/build_evernode_packages.sh
for op in deploy start stop restart recover verify; do
  deployment/evernode/operations.sh "$op" >/dev/null
done
CARGO_BUILD_JOBS=1 cargo test -p execution-core --test evernode_deployment_tests "$@"

mkdir -p deployment/reports
cat > deployment/reports/operator_readiness_report.md <<'RPT'
# Operator Readiness Report

- deployment artifacts: generated by `scripts/build_evernode_packages.sh`
- source control policy: generated `.tar.gz` and `.sig` files are not source controlled
- operations covered: deploy, start, stop, restart, recover, verify
- package rebuildability: validated
- operator readiness: validated
RPT

echo "operator validation complete"
