#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

bash scripts/build_evernode_packages.sh
(cd deployment/evernode/runtime && sha256sum -c packages.sha256 >/dev/null)
CARGO_BUILD_JOBS=1 cargo test -p execution-core --test arena_vanguard_certification_tests "$@"

mkdir -p deployment/reports
cat > deployment/reports/arena_vanguard_launch_candidate.md <<'RPT'
# Arena Vanguard Launch Candidate

- deployment artifacts: generated by `scripts/build_evernode_packages.sh`
- source control policy: generated `.tar.gz` and `.sig` files are not source controlled
- manifest-driven packages: runtime, world, deployment
- certification gate: validated
- launch candidate: validated
RPT

echo "launch candidate validation complete"
