pub mod archival;
pub mod checkpoint;
pub mod civilization;
pub mod continuity;
pub mod diagnostics;
pub mod economy;
pub mod evolution;
pub mod inventory;
pub mod lifecycle;
pub mod persistence;
pub mod restoration;
pub mod scheduler;
pub mod simulation;

pub use archival::CivilizationArchive;
pub use checkpoint::{LifecycleCheckpoint, SchedulerCheckpoint, WorldCheckpoint};
pub use civilization::CivilizationEntity;
pub use continuity::{ContinuityDivergence, WorldContinuityRoot};
pub use diagnostics::PersistentWorldDiagnostics;
pub use economy::{EconomicLedgerCheckpoint, EconomyMutation};
pub use evolution::EvolutionStage;
pub use inventory::{AssetContinuityRecord, InventoryMutation};
pub use lifecycle::EntityLifecycle;
pub use restoration::RestorationManifest;
pub use scheduler::{DeterministicTick, ScheduledOperation, WorldScheduler};
pub use simulation::{PersistentWorldState, WorldSimulation};
